# Project information:
site_name: 'AppleCommander'
nav:
  - Overview: 'index.md'
  - Installing: 'install.md'
  - Screenshots: 'using.md'
  - Using 'ac': 'ac.md'
  - Using 'acx': 'acx.md'
  - Develper Notes:
    - 'Maven/Gradle GAV': dev-notes/gav.md
    - 'UML diagrams': dev-notes/uml.md
    - 'Ant Task': dev-notes/ant.md
    - 'Javadoc': javadoc.md
    - 'cc65 Pipeline': dev-notes/cc65-pipeline.md
  - History:
    - 'Current releases': history/current.md
    - '1.3.5.14 (27-Nov-2013)': history/version13514.md
    - '1.3.5 (01-Jun-2008)': history/version135.md
    - '1.3.4 (31-Mar-2007)': history/version134.md
    - '1.3.3 (18-Jun-2004)': history/version133.md
    - '1.3.2 (05-Jun-2004)': history/version132.md
    - '1.3.1 (12-Dec-2003)': history/version131.md
    - '1.3.0 (04-Dec-2003)': history/version130.md
    - '1.2.3 (13-Apr-2003)': history/version123.md
    - '1.2.2 (15-Mar-2003)': history/version122.md
    - '1.2.1 (01-Mar-2003)': history/version121.md
    - '1.2.0 (11-Feb-2003)': history/version120.md
    - '1.1.1 (30-Nov-2002)': history/version111.md
    - '1.1 (12-Nov-2002)': history/version110.md
    - '1.0 (28-Oct-2002)': history/version100.md
site_description: 'Information site for the AppleCommander suite of tools'
site_author: 'a2geek'
site_url: 'https://applecommander.github.io'

# Repository
remote_branch: main
repo_name: AppleCommander
repo_url: https://github.com/AppleCommander/AppleCommander

# Copyright
copyright: Copyright &copy; 2002 - 2025 Robert Greene

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'images/apple-logo.png'
  favicon: 'images/apple-logo.png'
