# Project information:
site_name: 'AppleCommander'
nav:
  - Overview: 'index.md'
  - Installing: 'install.md'
  - Screenshots: 'using.md'
  - Using 'ac': 'ac.md'
  - Using 'acx': 'acx.md'
  - Developer Notes:
    - 'Maven/Gradle GAV': dev-notes/gav.md
    - 'Updated API and UML': dev-notes/redesign.md
    - 'Historical UML diagrams': dev-notes/uml.md
    - 'Disassembler API': dev-notes/disassembler.md
    - 'Ant Task': dev-notes/ant.md
    - 'Javadoc': javadoc.md
    - 'cc65 Pipeline': dev-notes/cc65-pipeline.md
  - History:
    - 'Current releases': history/current.md
    - 'Legacy releases': history/legacy.md
site_description: 'Information site for the AppleCommander suite of tools'
site_author: 'a2geek'
site_url: 'https://applecommander.github.io'

# Repository
remote_branch: master
repo_name: AppleCommander
repo_url: https://github.com/AppleCommander/AppleCommander

# Copyright
copyright: Copyright &copy; 2002 - 2025 Robert Greene

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'images/apple-logo.png'
  favicon: 'images/apple-logo.png'

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Plugins
plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
